language: ruby
cache: bundler
rvm:
  - "2.2.3"
  - "2.1.7"
  - "2.0.0"
  - "ruby-head"

matrix:
  allow_failures:
    - rvm:
      - "ruby-head"
  fast_finish: true
notifications:
  email:
    - travis-ci@sorah.jp
script: bundle exec rspec -fd ./spec
